---
networks:
  proxy:
    name: proxy
    driver: bridge
    external: true

services:
  traefik:
    restart: unless-stopped
    security_opt:
      # - no-new-privileges:true
      - label=type:container_runtime_t
    mem_limit: 2G
    volumes:
      - ${CURDIR}/.data/traefik/ssl/:/etc/traefik/ssl/:z
      - ${CURDIR}/.logs/traefik/:/var/log/traefik/:z
      - $XDG_RUNTIME_DIR/podman/podman.sock:/var/run/docker.sock:ro,Z
    environment:
      - DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock
    ports:
      - target: 80
        published: ${TRAEFIK_HOST_HTTP_PORT:-80}
        protocol: tcp
        mode: host
      - target: 443
        published: ${TRAEFIK_HOST_HTTPS_PORT:-443}
        protocol: tcp
        mode: host
    networks:
      - proxy

  logger:
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    mem_limit: 64M
    volumes:
      - ${CURDIR}/.logs/traefik:/var/log/traefik:z
    networks:
      - proxy
    depends_on:
      - traefik

  # whoami:
  #   image: traefik/whoami:latest
  #   container_name: whoami
  #   networks:
  #     - proxy
  #   depends_on:
  #     - traefik
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.whoami.entrypoints=https
  #     - traefik.http.routers.whoami.rule=Host(`jogjascript.com`)||Host(`www.jogjascript.com`)
  #     # Add redirect middlewares for http and https
  #     - traefik.http.routers.whoami.middlewares=redirect-http-www@file,redirect-https-www@file

  # portainer:
  #   image: portainer/portainer-ce:latest
  #   restart: unless-stopped
  #   security_opt:
  #     - no-new-privileges:true
  #   networks:
  #     - proxy
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - ${CURDIR}/.data/portainer:/data
  #   labels:
  #     - traefik.http.routers.portainer.entrypoints=http
  #     - traefik.http.routers.portainer.rule=Host(`portainer.${TRAEFIK_DOMAIN_NAME}`)
  #     - traefik.http.services.portainer.loadbalancer.serve mr.port=9000
  #   depends_on:
  #     - dockersocket
  #     - traefik
